### ISSUE TITLE
Tutorial sample app 2 - Step 3-1. Databases disappear from Admin UI

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#53] opened 2015-12-15 10:19 UTC
I followed instructions on http://starcounter.io/tutorials/invoicedemo-part-3/3-1-install-launcher-from-appstore/.

Downloaded the Launcher application, started it. Followed instructions to go to localhost:8080 (8484 in my env). When browsing I get a 404.

![2015-12-15_11-17-58](https://cloud.githubusercontent.com/assets/1765023/11807953/97174212-a31d-11e5-903b-d779e461013e.png)

When going to the Admin UI. All databases/applications are gone! =|

![2015-12-15_11-14-33](https://cloud.githubusercontent.com/assets/1765023/11807974/b45c9c0a-a31d-11e5-817c-7b7e9a69abe1.png)

Examining the SC logs I have a null reference error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at StartCounter_InvoiceDemo1.Program.<>c.<Main>b__1_0() in D:\Code\plupp-git\StartCounter_InvoiceDemo1\StartCounter_InvoiceDemo1\Program.cs:line 34
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-114\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 260
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-114\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Launcher.LauncherHelper.WrapInLauncher(Request req, String appName) in C:\www\StarcounterSamples\Launcher\src\Launcher\Api\LauncherHelper.cs:line 179
   at Launcher.LauncherHelper.<>c.<Init>b__0_0(Request req) in C:\www\StarcounterSamples\Launcher\src\Launcher\Api\LauncherHelper.cs:line 46
   at Starcounter.Handle.RunMiddlewareFilters(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-114\Level1\src\Starcounter.Internal\Handle.cs:line 473
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-114\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 473
HResult=-2147467261

Stopping the debugger of my InvoiceDemo makes the applications show again.

**Comment by warpech** [comment] 2016-01-18 10:08
@andwah can you pls take a look at this?

**Comment by andwah** [comment] 2016-01-18 10:50
I get the same behaviour when i try to navigate to ```http://127.0.0.1:8484/``` => ```Error 404: Resource "/" not found.``` 

If i change the url to ```http://127.0.0.1:8484/Launcher``` then it works as expected.

**Comment by andwah** [comment] 2016-01-18 10:59
I think the problem is in the resent change about Session.Current.Data is set/handled. 

@warpech See https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo2/Program.cs#L9

Is that the correct way of handling it? i can remember.

**Comment by warpech** [comment] 2016-01-18 14:57
Without reading I thought this is an Administrator problem, but after reading this are not neccessary related problems. 

Sorry for improperly assigning this on you, @andwah.

**1) Regarding screenshot:** 

![2015-12-15_11-17-58](https://cloud.githubusercontent.com/assets/1765023/11807953/97174212-a31d-11e5-903b-d779e461013e.png)

Launcher should be accessed as `http://localhost:8484/launcher` (not `http://localhost:8484/`). 

Resolution: this was fixed in the text of page http://starcounter.io/tutorials/invoicedemo-part-3/3-1-install-launcher-from-appstore/ by @miyconst on 21.12.2015.

**2) Regarding screenshot: **

![2015-12-15_11-14-33](https://cloud.githubusercontent.com/assets/1765023/11807974/b45c9c0a-a31d-11e5-817c-7b7e9a69abe1.png)

There are cases when Administrator does not show the list of databases properly (I have to isolate that one). 

Resolution: wait for more isolated report.

**3) Regarding the stack trace.** It might be related to `Session.Current.Data` handling changes in Launcher made in December, but there were no other reports regarding that yet. 

Resolution: wait for more isolated report.

Nothing more to fix here then. Potential remaining problems will be investigated again as they appear

**Closed by warpech** 2016-01-18 14:57 UTC
